# Generated by Django 3.1.2 on 2020-10-11 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiAppSintactico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tejidomama',
            old_name='Inflamacion',
            new_name='inflamacion',
        ),
        migrations.RenameField(
            model_name='tejidomama',
            old_name='partp',
            new_name='partP',
        ),
    ]
